DROP TABLE IF EXISTS METRICS_MEASUREMENT_METRICS;

CREATE TABLE METRICS_MEASUREMENT_METRICS
(
  MEASUREMENT_ID  	VARCHAR(64)             NOT NULL,
  NAME            	VARCHAR(64)             NOT NULL,
  VALUE           	VARCHAR(1024),
  CREATED_FROM      VARCHAR(30)             NOT NULL,
  UPDATED_AT      	DATETIME,
  UPDATED_FROM      VARCHAR(30),
  CREATED_AT      	DATETIME
);


CREATE INDEX FK_METRICS_MEASUREMENT_ID ON METRICS_MEASUREMENT_METRICS (MEASUREMENT_ID);


alter table METRICS_MEASUREMENT_METRICS
   add constraint FK_MEASUREMENT_METRCIS_ID foreign key (MEASUREMENT_ID)
      references METRICS_MEASUREMENT (MEASUREMENT_ID);





