DROP TABLE IF EXISTS METRICS_MEASUREMENT;

CREATE TABLE METRICS_MEASUREMENT
(
  MEASUREMENT_ID  VARCHAR(64)             		NOT NULL,
  RECORD_ID       VARCHAR(64)             		NOT NULL,
  PARENT_ID       VARCHAR(64),
  CORRELATION_ID  VARCHAR(64),
  REQUESTER_ID    VARCHAR(64),
  COMPONENT_NAME  VARCHAR(64)             		NOT NULL,
  FUNCTION_NAME   VARCHAR(64)             		NOT NULL,
  THREAD_NAME     VARCHAR(64)             		NOT NULL,
  REQUEST_USER    VARCHAR(16)             		NOT NULL,
  TIME		      DATETIME					  	NOT NULL,
  DURATION        INT                        	NOT NULL,
  WORK_UNITS      INT                        	NOT NULL,
  FAIL_STATUS     TINYINT(1),
  CREATE_ORDER    INT,
  CREATED_FROM    VARCHAR(30)             		NOT NULL,
  UPDATED_AT      DATETIME,
  UPDATED_FROM    VARCHAR(30),
  CREATED_AT      DATETIME,
  PRIMARY KEY (MEASUREMENT_ID)
);


CREATE INDEX FK_METRICS_MEASUREMENT_RECORD ON METRICS_MEASUREMENT (RECORD_ID);


alter table METRICS_MEASUREMENT
   add constraint FK_MEASUREMENT_RECORD_ID foreign key (RECORD_ID)
      references METRICS_RECORD (RECORD_ID);






