DROP TABLE IF EXISTS METRICS_RECORD;

CREATE TABLE METRICS_RECORD
(
  RECORD_ID            VARCHAR(64)        NOT NULL,
  SERVICE_GROUP		   VARCHAR(64)        NOT NULL,
  DOMAIN               VARCHAR(32)        NOT NULL,
  HOST_NAME            VARCHAR(32)        NOT NULL,
  SERVICE		       VARCHAR(64)        NOT NULL,
  APPLICATION_VERSION  VARCHAR(16)        NOT NULL,
  HOST_USER            VARCHAR(32)        NOT NULL,
  INSTANCE_PID         VARCHAR(16)        NOT NULL,
  AGGREGATION_RANGES   VARCHAR(256),
  FILTER_STATUS        TINYINT(1),
  CREATED_FROM         VARCHAR(30)        NOT NULL,
  UPDATED_AT           DATETIME,
  UPDATED_FROM         VARCHAR(30),
  CREATED_AT           DATETIME,
  PRIMARY KEY (RECORD_ID)
);


